exclude_paths:
  - /vendor

keep:
  - add_insert_cmd # called by ::ERB::Compiler
  - add_put_cmd # called by ::ERB::Compiler
  - 'n' # called by Parser::AST::Builder
  - string_value # called by Parser::AST::Builder

dynamic:
  name: new
  has_receiver:
    name: Predicate
    has_receiver:
      name: Matchers
      has_receiver: Leftovers
  calls:
    argument: 0
